import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./preflight.css";
import "./globals.css";
import "./icomoon/style.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const barlowSans = Barlow({
  variable: "--font-barlow-sans",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlowSans.variable}`}>
        <div className="layout">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
